version: '3.4'
services:
  backend:
    image: city.io-backend
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
  frontend:
    image: city.io-frontend
    build:
      context: .
      target: frontend
    ports:
      - "4200:80"
