version: '3.4'
services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mysql:/var/lib/mysql
  backend:
    container_name: city.io-backend
    image: city.io/backend
    env_file: ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: src
    depends_on:
      - mysql
    ports:
      - "8000:8000"
  frontend:
    container_name: city.io-frontend
    image: city.io/frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: client
    ports:
      - "4200:80"

volumes:
  mysql:
