# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "github-workflow" ]
  pull_request:
    branches: [ "github-workflow" ]

jobs:

  build:
    runs-on: [self-hosted, linux]
    
    steps:
    - name: Install dependencies
      run: cd src; go get; cd ../client; npm install --quiet
      
    - name: Build
      run: cd src; go build; cd ../client; npm run build; cd ..

    - name: Test
      run: cd src; go test -v api/tests; cd ..
